#ifndef SERVICE_TEMPLATE_SRC_CORE_COLOR_SPACE_H_
#define SERVICE_TEMPLATE_SRC_CORE_COLOR_SPACE_H_

namespace server::core::pnm {
enum ColorSpace { RGB, HSL, HSV, YCbCr601, YCbCr709, YCoCg, CMY, NONE };
}

#endif  // SERVICE_TEMPLATE_SRC_CORE_COLOR_SPACE_H_
